### PR TITLE
Related to my feature request from issue #5

### PR DESCRIPTION
**Pull request by wikimatze**

### CODE REVIEW

**Comment by wikimatze** [comment]
I've updated the script and it worked on my machine. Should we put this information into the `readme.md` file instead? I've no problem to use this script in my Vim-installation-setup. I tried out the [nerd-filetype-glyphs-fonts-patcher](https://github.com/ryanoasis/nerd-filetype-glyphs-fonts-patcher) but had problems running python and don't know what this repo is for. I'm using it to get the Droid font so far.

Waiting for feedback.

**Comment by blueyed** [comment]
> Should we put this information into the readme.md file instead?

Yes.

I suggest something like this for the README:

    1. Pick a font from
       https://github.com/ryanoasis/nerd-filetype-glyphs-fonts-patcher/tree/master/patched-fonts
       (find the link to the "raw" file).
    2. Download and install it

    On Unix systems this can be usually done by putting it into `~/.fonts`:

        % cd ~/.fonts
        % wget $URL_TO_RAW_FONT

    e.g.

        [example for the "recommended" font]

**Comment by wikimatze** [comment]
I would be fine with this, what do you think @ryanoasis?

**Comment by ryanoasis** [comment]
>[nerd-filetype-glyphs-fonts-patcher](https://github.com/ryanoasis/nerd-filetype-glyphs-fonts-patcher) but had problems running python and don't know what this repo is for. I'm using it to get the Droid font so far.

[nerd-filetype-glyphs-fonts-patcher repo](https://github.com/ryanoasis/nerd-filetype-glyphs-fonts-patcher) has the python script for patching any other fonts not currently included on the repo __and__ provides some already patched fonts.

@wikimatze, that example from @blueyed looks pretty good. Are you wanting to forgo adding your install script and use a wiki update instead?

The current section on font configuration is pretty poor wow I didn't really realize until I looked at it again (https://github.com/ryanoasis/vim-webdevicons#font-configuration)

I say readme addition is the way to go unless you really want to add the font install script (I wont turn away any contributions)

**Comment by wikimatze** [comment]
@ryanoasis I will make a Pull request for the README addition. Thanks @blueyed for your feedback in this issue, glad ryan I could "hit-your-head" with the documentation remarks.

**Pull request closed without merging**
